import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/nav-bar";
import { NavbarContainer } from "@/components/nav-bar-container";
import ReactQueryProvider from "@/utils/react-query";
import { CookiesProvider } from "next-client-cookies/server";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CookiesProvider>
          <ReactQueryProvider>
            <NuqsAdapter>
              <NavbarContainer>
                <Navbar />
              </NavbarContainer>
              {children}
              <Toaster position="top-center" reverseOrder={false} />
            </NuqsAdapter>
          </ReactQueryProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
