import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/nav-bar";
import { NavbarContainer } from "@/components/nav-bar-container";
import ReactQueryProvider from "@/utils/react-query";
import { CookiesProvider } from "next-client-cookies/server";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Toaster } from "react-hot-toast";
import { getAuthCookieServer } from "@/lib/auth-cookies";
import {
  dehydrate,
  HydrationBoundary,
  QueryClient,
} from "@tanstack/react-query";
import { sdk } from "@/graphql/sdk";
import { XiorError } from "xior";
import { RefreshAccessToken } from "@/components/refresh-token";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = new QueryClient();

  const token = await getAuthCookieServer();

  if (token) {
    try {
      const { me } = await sdk.Me(
        {},
        {
          revalidate: 60,
          tags: ["Me"],
        }
      );

      if (me) {
        queryClient.setQueryData(["Me"], { me });
      }
    } catch (err) {
      if (err instanceof XiorError && err.response?.status === 401) {
        return (
          <html lang="tr">
            <body>
              <RefreshAccessToken />
            </body>
          </html>
        );
      }
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HydrationBoundary state={dehydrate(queryClient)}>
          <CookiesProvider>
            <ReactQueryProvider>
              <NuqsAdapter>
                <NavbarContainer>
                  <Navbar />
                </NavbarContainer>
                {children}
                <Toaster position="top-center" reverseOrder={false} />
              </NuqsAdapter>
            </ReactQueryProvider>
          </CookiesProvider>
        </HydrationBoundary>
      </body>
    </html>
  );
}
